pipelines:
  SampleJavaApp:
    group: SampleGroup
    label_template: "${COUNT}"
    materials:
      git:
        url: https://github.com/your-repo/SampleJavaApp.git
        branch: master
    stages:
      - build:
          jobs:
            - build-job:
                tasks:
                  - exec:
                      command: mvn 
                      arguments: -B -DskipTests clean package
